### ISSUE TITLE
status of this project?

### ISSUE THREAD

**Issue by michielbdejong** [TheHostingTool/TheHostingTool#144]
Hi! We are looking for an open source hosting tool, that does:

* process orders from web shop
* CRM to keep track of users contact details and billing status
* support tickets system
* trigger domain name registration at a third-party provider
* trigger server deployment on third-party IaaS provider
* add the right DNS zone to a DNS server
* update the config on an application hosting server (this part is custom)

It looks like this project is the only one out there that attempts to do this, right? But I see the last commit is 6 months ago, so correct me if I'm wrong, but that makes me think there are probably not many people using this in production? I mean, I would expect your market share to be smaller than WHMCS and HostBill, but if we are to start using THT in production, it would still be nice to know that we were not the only ones doing so. We would of course help with the development, but if we are going to be the main users, then it might be more attractive to develop our own system (maybe based on THT?).

Our other alternative would be to develop plugins for Odoo (we're discussing it [here](https://github.com/indiehosters/documents/issues/16)).

Any input to our decision process very welcome! :)

**Comment by 2braincells2go** [comment]
Not to take away from "The Hosting Tool" as it can be a fine product for some. But since BoxBilling went open source, we started using it on some sites and like it. One still has to revamp the code on GitHub to kill their licensing module, but pretty much does everything:

https://github.com/boxbilling/boxbilling

**Comment by michielbdejong** [comment]
@2braincells2go thanks for the tip! I'm confused though - yes, on https://github.com/boxbilling/boxbilling/blob/master/LICENSE it's clearly Apache-licensed, but from http://stackoverflow.com/questions/29315895/best-whmcs-open-source-alternative and from http://www.boxbilling.com/order it seems the 'free license' is limited?

Looking at https://github.com/boxbilling/boxbilling/pull/297 it seems that the person who added the Apache license didn't understand what they were doing, and so although legally it would be allowed, personally it seems a bit unfair to use their software without paying.

**Comment by kmark** [comment]
I'm afraid the status of TheHostingTool is "practically dead." For quite awhile I've been the only one working on it in my free time. I had much more time to give a few years ago. Development has slowed to just about nothing as no one (who is qualified) has stepped forward to continue working on it. This is most likely because the demand for products like TheHostingTool is now very low. WHMCS does pretty much everything THT does but better. And WHMCS isn't liable to break the bank either. THT is geared towards free web hosting providers (Post2Host, all that good stuff) but those are nowhere near as prevalent as they used to be. THT does not have very good support for payment gateways (shaky PayPal support only). In other words there's no real way to make money with THT as opposed to other offerings.

TheHostingTool also desperately needs to be rewritten. The current codebase just isn't cutting it. Hardcoded language strings, no support for plugins, buggy installer, completely useless security settings, probably some CSRF and maybe a few SQL injection exploits to be discovered (haven't really checked), and no usage of modern PHP features. All ignoring the fact that some features just flat out do not work. With the past few commits I'm quite proud of some of the strides made towards a better codebase. They're just a drop in the bucket though. And now I'm contemplating if it's even worth continuing work on it. I've spent so many hours trying to improve the code one could easily argue I could've rewritten the thing by now.

>* process orders from web shop

THT does have a built-in order form but it is the only way to register. It must be used unless you're manually adding things into the database.
>* CRM to keep track of users contact details and billing status

THT is able to do this but only supports PayPal and that can be buggy.

>* support tickets system

There's a very basic ticketing system available.

>* trigger domain name registration at a third-party provider

Would need to be hardcoded in.

>* trigger server deployment on third-party IaaS provider

Could theoretically be done in a custom server type.

>* add the right DNS zone to a DNS server

Would best be done as well in the custom server type code.

>* update the config on an application hosting server (this part is custom)

Same deal as above. These things are probably doable but THT does expect to be used with traditional server types like local WHM stuff. Might make some workarounds painful.

>there are probably not many people using this in production?

I never got around to collecting THT usage statistics but I would imagine there are only a few running instances of THT still out there. 

>might be more attractive to develop our own system

This is probably the way to go, in all honesty.

>(maybe based on THT?)

I'd personally recommend starting fresh. It's what I've considered doing. Or at the very least going through the THT codebase and understanding why some of the design decisions (or lack thereof) should not be repeated. Again, I really like what I've been doing in the past few commits (autoloading server modules! infinitely flexible package types! powerful custom order fields!) and while losing it would suck, perhaps the most foolish thing to do would be to *keep* spending time on it. After all, the features and structural changes that I've been adding should've been there day 1. Or maybe day 2.

As for boxbilling I have no experience with it and cannot recommend for or against it. The language file issue is highly troubling though. From my understanding of the Apache license only the copyright in the license file or code comments needs to stay intact. It allows for the unrestricted modification of the software which should include removing any user-facing "Powered by" links. It definitely seems incompatible with the mandatory branding mentioned on the website. In its current situation I would say it's unsafe to use for free without a written clarification made by boxbilling. At least the branding issue is the only Apache incompatibility that I see but IANAL.

**Comment by michielbdejong** [comment]
Thanks for your long answer! OK, we'll probably look at using Odoo for the generic basics (sales, billing, tickets), and then write our own collection of scripts that do the deploy.

I think I'll use the 'reconciler model', so Odoo writes down what /should/ be running, and a separate process (the reconciler) is constantly trying to make that true. This also gives a nice separation between Odoo and our own scripts.

**Comment by kmark** [comment]
My pleasure. I haven't commented much on the status of the project recently and I suppose here was a good a place as any.

Never heard of Odoo before but it looks like a pretty complete solution to get you up and running quickly. Good luck with your new venture!
