### ISSUE TITLE
full of errors

### ISSUE THREAD

**Issue by tanmoy30** [TheHostingTool/TheHostingTool#152]
I couldn't believe my eyes!!!! 55 errors on starting of the installation and nothing installed, gave me a blank page afterwards.

**Comment by madfunny** [comment]
It's like a ten year old script that keeps getting half way "reworked". Can't expect much!

**Comment by xaoseric** [comment]
Did you use latest push? If so, please provide the errors you are getting.

**Comment by kmark** [comment]
Hi! Unfortunately development on TheHostingTool ceased in 2014 and a few patches were added in 2017. Due to this I would not expect the software to work out of the box in any modern environment. Additionally, the current code on GitHub represents the head of development at the time development halted, not code that was prepared for a release. As such there may be even more bugs than there would have been normally.

I will always review pull-requests, time-allowing. Thank you for your interest!
